name: "CI (Integração Contínua): Main Workflow"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      #Comandos para rodar no CI
      - name: Run a one-line script
        run: echo Olá Mundo!