name: "CI (Integração Contínua): Main Workflow"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Instalation
        run: yarn

      - name: Run lint fix
        run: yarn lint:fix

      - name: Run linter
        run: yarn lint